### PR TITLE
Change some log message levels from info to debug in RSMTask

### PR DESCRIPTION
**Pull request by ying-zheng**

### CODE REVIEW

**Comment by satishd** [comment]
@ying-zheng IMHO, info level logging would cause lot of logging as it is for each topic partition. Why do you want to change it to info level?

**Comment by satishd** [comment]
If you need to see those debug logs while you debug an issue. You can change logging levels by JMX API or new AdminClient API mentioned in [KAFKA-7800](https://issues.apache.org/jira/browse).

**Comment by ying-zheng** [comment]
> @ying-zheng IMHO, info level logging would cause lot of logging as it is for each topic partition. Why do you want to change it to info level?

The problem is just too many info logs. This code diff is changing from info to debug.

**Comment by satishd** [comment]
@ying-zheng Sorry, that was my bad, I misread it. I agree we should move this to debug.

**Review by satishd — APPROVED** [review]

**Pull request merged**
