### PR TITLE
Improve S3RemoteStorageManager.close()

### PR DESCRIPTION
**Pull request by ivanyu**

### CODE REVIEW

**Review by satishd — APPROVED** [review]
thanks @ivanyu for the PR, LGTM.

**Comment by satishd** [comment]
@ivanyu can you raise the PR again with this change? I wanted to avoid merge commit while merging the change, I rebased to avoid that.  But I realized you have deleted your branch because of which I am not able to merge the change. Sorry for the confusion.

**Comment by ivanyu** [comment]
@satishd I restored the branch - is it enough? If not, surely I'll re-make the PR

**Comment by satishd** [comment]
thanks @ivanyu for restoring the branch, change is merged.

**Pull request merged**
